### ISSUE TITLE
sane configuration

### ISSUE THREAD

**Issue by skermes** [skermes/review#10]

**Comment by ScottDugas** [comment]
I don't know if a config.rb file is sufficient, but it is a bit better than before. The only other real option, that I can think of is to create a YAML file

**Comment by skermes** [comment]
I was leaning towards something like a yaml file.  It'd be nice if there were more things that could be updated without changing Ruby code, since at the moment that forces us to restart the sinatra server.  If we had a yaml file and a config(:key) -> value function that would make sure to reload the file if it had to, that would be one more thing that could be changed by just dropping a new file in place.

But that's not super important, really.

**Comment by ScottDugas** [comment]
Yeah, it seems to me like config would generally happen once on a machine and then be done with it, and maybe update if there were updates to the rest of the code, but then your restarting it anyways

**Comment by skermes** [comment]
That's a good point.  It's probably not worth cluttering things for.

I think there are only two things I'd like to figure out then.  First, what's the easiest way to handle optional config options?  I guess we could add a section at the top like `unless defined? PARAM then PARAM = []` (or whatever the default is) for each option.

And do we want to put all of the configuration handling in a separate file?  Looking at it now, it's actually less awkward than I thought it was when I started this comment.  Maybe it's best to just leave it for now and refactor if it becomes more unwieldy.
