### ISSUE TITLE
better notes

### ISSUE THREAD

**Issue by skermes** [skermes/review#8]
autosizing textareas
colored notes

**Comment by ScottDugas** [comment]
Another option to the autosizing, is to just make it resizable: http://jqueryui.com/demos/resizable/#textarea

**Comment by skermes** [comment]
That would work (and we actually get it for free in Chrome).  How hard do you think it would be to do without jQuery?  The control on that page does a lot more than we want (basically, everything except the default functionality).  It'd be nice if we could keep our js to a minimum.

**Comment by skermes** [comment]
Check out the better-notes branch.  I made the notes autosize when you add text, added a background/border to them, and let the user drag them around.

The autosizing could use some work (most notably, it's kind of jerky and only fires on non-whitespace characters), but the on the whole it's pretty slick.  Thoughts?

**Comment by skermes** [comment]
Suggestions from Will: drop shadow on notes so that they stand out better when on top of text, being able to dismiss notes

**Comment by skermes** [comment]
All the suggestions in here are done.  The autosizing could still stand some tweaking (it doesn't seem to play nice with double spaces after a sentence on the longest line, for example) but the bulk of what needs to be done is done.
